### ISSUE TITLE
Implement Openstack

### ISSUE THREAD

**Issue by shwsun** [kubicorn/kubicorn#105]
Hey, 
Unfortunately I don't have access to EC2 or Azure, it is possible to create some sort of profile for Openstack environment? If so I would be happy to help (I work on openstack a lot)

**Comment by kris-nova** [comment]
Yes this is a great idea, would love to code an implementation in! There is documentation on how write a Reconciler in the Cloud directory https://github.com/kris-nova/kubicorn/tree/master/cloud and there are examples of other implementations in the code base. 

Do you want to start coding and we can work together? Also happy to jump on a video call and go through this in greater detail if needed

**Comment by shwsun** [comment]
Hi,
I will be a little busy the coming week due to some research workload so that spending non-preempted time might be a little luxury for me :(  I will start with the reconciler and probably discuss with you if I have any questions. I am very interested into the bare metal case too (some of my past research can actually use that right away)

**Comment by kris-nova** [comment]
I am wrapping up writing a book this week and next, but once that is done I should be back to my old tricks again.. meaning I can help out with this effort as well!

**Comment by joedborg** [comment]
I'm happy to help with this too.  Closest thing, that I'm aware of, is Juju.

**Comment by xlucas** [comment]
Has any progress be made on this subject ? Are you still looking for help ?

**Comment by xlucas** [comment]
I've started working on an Openstack implementation.

**Comment by xlucas** [comment]
I guess this issue can be closed now :)

**Comment by xmudrii** [comment]
@xlucas thanks for the update! Closing
