### ISSUE TITLE
Integrate with Heptio's Ark

### ISSUE THREAD

**Issue by krisnova** [kubicorn/kubicorn#195]
@kris-nova to come up with a plan and flesh out implementation details

**Comment by prateekgogia** [comment]
## Take a snapshot.

1. Create a cluster using Kubicorn.
2. Deploy Applications.
3. Take a snapshot using Kubicorn.
   a. Take a snapshot of the cluster using `GetActual`.
   b. Take a snapshot of the application using `Ark`.
   c. Push to state store.

## Edit a snapshot
1. `kubicorn edit `
   a. Read the snapshot from the state store.
   b. Write the snapshot to the local fs.
   c. Open the file in user's text editor.
   d. Save the temp file.
   e. Write to state store.

## Restore a snapshot

1. `kubicorn apply --snapshot <name>`
   a. Apply cluster.
   b. Ark restore.
