### ISSUE TITLE
Add a CLA to the repository

### ISSUE THREAD

**Issue by aledbf** [kubicorn/kubicorn#212]
Just in case :)

Edit: using something like https://cla-assistant.io/ (just an example)

**Comment by kris-nova** [comment]
Can we please implement the `cla-assistant` link that @aledbf mentioned? Ping me if anyone needs access/creds etc

**Comment by zoidbergwill** [comment]
CLA Assistant has [this](https://gist.github.com/CLAassistant/bd1ea8ec8aa0357414e8) default CLA we could fork?

**Comment by aledbf** [comment]
That is what I did with this:

```console
wget https://gist.githubusercontent.com/CLAassistant/bd1ea8ec8aa0357414e8/raw/e7b55cd3326eb4efda7d1252a256306c22adff26/SAP_CLA
sed -i "s/SAP SE/kubicorn/" SAP_CLA
sed -i "s/SAP/kubicorn/" SAP_CLA
```

but I cannot select the `kris-nova/kubicorn` repository. Only the ownser can do that

**Comment by stp-ip** [comment]
Gitlab and a few other open source projects add a paragraph to their contributing.md, to clarify that all contributions fall under the CLA (individual + corporate): https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CONTRIBUTING.md#contributor-license-agreement

icla: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/legal/individual_contributor_license_agreement.md
ccla: https://gitlab.com/gitlab-org/gitlab-ce/blob/master/doc/legal/corporate_contributor_license_agreement.md

They reused the CLAs used by google, which I find quite clean and usable too.

Might that be something we could consider instead? Less friction, less infra to maintain, easier to switch platform and contributions via patches or on other platforms don't need special tooling.

**Comment by stp-ip** [comment]
Sidenote:
Due to this issue I felt the need to finally have a base open source repo to make it easy for a project to have the essentials (CoC, LICENSE, contributing guides, CLA etc.) any feedback or PRs are appreciated.
(Just a first draft for now, but hope that might help reduce friction for other projects in the future)

https://github.com/osstemp/base

**Comment by aledbf** [comment]
Maybe this app can help https://github.com/apps/dco
