### ISSUE TITLE
Implement Digital Ocean Cloud Controller for DO clusters

### ISSUE THREAD

**Issue by kris-nova** [kubicorn/kubicorn#276]
Can we please implement the following with digital ocean clusters:

https://github.com/digitalocean/digitalocean-cloud-controller-manager

**Comment by xmudrii** [comment]
‎TIL this is official project. +1
I could be doing it once I finish with signals, if somebody doesn't take before me.

**Comment by xmudrii** [comment]
I'm taking on this one

**Comment by xmudrii** [comment]
This issue is fixed by https://github.com/kubicorn/bootstrap/pull/23
