### ISSUE TITLE
Use new community Cluster API

### ISSUE THREAD

**Issue by kris-nova** [kubicorn/kubicorn#471]
This is a big one and I will probably do it, unless somebody else wants to get themselves into some crazy Go work! 

But basically the Kubernetes community has been coming together and working towards a standardized **Cluster API** which can be found [here](https://github.com/kubernetes/kube-deploy/tree/master/cluster-api)

We need to support the new API in Kubicorn and move towards making this official moving forward.

**Comment by adnxn** [comment]
> wants to get themselves into some crazy Go work!

Yes please. 

@kris-nova,  Do you have any thoughts on a path forward? Or suggestions for where to start looking first?

**Comment by xmudrii** [comment]
@adnxn @kris-nova is already working on this one, and she's actually near the end. You can track the progress in #482.

**Comment by adnxn** [comment]
@xmudrii ah gotcha sounds good 😄
