### ISSUE TITLE
Add more options to fetch the bootstrap scripts

### ISSUE THREAD

**Issue by matyix** [kubicorn/kubicorn#489]
As we have now moved away from `bindata` generated bootstrap to a more flexible ways to fetch the scripts I'd like to have more options (beside fs or github) to get the bootstrap files. [Go-getter](https://github.com/hashicorp/go-getter) allows to fetch from few different sources - is there interest beside of what we have now? If so @kris-nova @xmudrii put this on me and will send a PR.

**Comment by xmudrii** [comment]
This looks awesome! If you want to work on it, feel free to take it, we would appreciate it.

**Comment by matyix** [comment]
OK - you can assign this to me. Thanks @xmudrii.
