### ISSUE TITLE
How to scale

### ISSUE THREAD

**Issue by ulrichSchreiner** [kubicorn/kubicorn#512]
hi,

i wonder how to scale the number of nodes of a created cluster? So i created a cluster with digitalocean and everything ok. but now i simply entered the same command again and i thought that nothing happens: a `kubicorn apply myk8s` should reconcile the local `_state/..." yaml file with the current cluster running. 

but ... kubicorn tried to create a new cluster with the same name and tags ... and this does not work (digitalocean response with a 422 code). now kubicorn deletes some resources it could not create, but this destroyed the running cluster also, because things are cleaned up which existed before!

a deepter look at the code shows that the model in the store and the current running model most of the time differ (they use a `cloudId` field for many types, firewalls also have a `created` and a `status` field, they have the ingress/egress rules as an unordered array .... the reconciler does not have many chances to detect ressources which are already created because it uses JSON-serializing and here not only every field counts; when using arrays the ordering also counts.

So ... how should i scale up my nodes? i thought i simply increase the `MaxCound` field in the serverpool of the node-pool and then again i `apply`. But as written above: this does not work when the field is not changed at all and it fails if the field is altered.

What am i'm doing wrong?

**Comment by adipascu** [comment]
I am facing similar issues, it looks like the DigitalOceal reconciling process is not working.

**Comment by xmudrii** [comment]
Currently, scaling is not implemented at all. I've seen @ulrichSchreiner PR implementing this, but we're doing major API refactor and then we'll get back to the PR backlog.

@adipascu Do you have problems only when trying to upscale the cluster or when creating for the first time?

**Comment by adipascu** [comment]
I am having this issue when I run the create command twice. I expected it to be a NOOP, but it crashed instead.

Scaling and switching VM types would be a nice feature to have.

**Comment by xmudrii** [comment]
Yep, running apply/create mulitple times doesn't work at all. I hope we'll get it working soon
