### ISSUE TITLE
Ubuntu bootstrap scripts not respecting kubernetes version

### ISSUE THREAD

**Issue by kris-nova** [kubicorn/kubicorn#513]
Looks like it might be a bug in `kubeadm` https://github.com/kubernetes/kubeadm/issues/612

Place holder issue regardless, can provide more details if needed

**Comment by xmudrii** [comment]
Working on the fix

**Comment by xmudrii** [comment]
kubernetes/kubeadm#612 is closed as this is not assumed as a bug.
We're already explicitly telling `apt` what version to install, so I think it's okay to close this issue.

@kris-nova If you still have problems, please re-open the issue. :)
