### ISSUE TITLE
Rename the import to ext-apiserver

### ISSUE THREAD

**Issue by krisnova** [kubicorn/kubicorn#579]
Right now we are vendoring an older version of `kube-deploy` [here](https://github.com/kubicorn/kubicorn/blob/master/apis/cluster/cluster.go#L22)

We need to use the new API [here](https://github.com/kubernetes/kube-deploy/blob/master/ext-apiserver/pkg/apis/cluster/v1alpha1/cluster_types.go)

**Comment by xmudrii** [comment]
#591 will fix this issue.
