### ISSUE TITLE
AtomicReconciler semantically incorrect

### ISSUE THREAD

**Issue by ulrichSchreiner** [kubicorn/kubicorn#586]
hi,

in the code of the `AtomicReconciler` you can see the pattern:
~~~go
for i := 0; i < len(r.model.Resources()); i++ {
    resource := r.model.Resources()[i]
~~~
where `model.Resources()` returns a `map[int]Resource`.  The upper code only works, if the map is really an array, so the key's in the map are identically to the list of `0..len(r.model.Resources())`.

Suppose you have a map like:
~~~
{ 
  10 : ressource1,
  20 : ressource2
}
~~~
if you use the upper loop, you will loop from 0..1 and use these two numbers as keys in the map, but this won't work, as the keys in the map in this example are 10 and 20.

you should either use a return type of `[]Resource` for the `model.Resource()` function or use the `range` keyword to iterate over the map and get the correct keys. i think the current code is semantically incorrect.

yeah, you are creating the model's with consecutive numbers, but this is an implemetation issue, which is not guaranteed by the signature of the type. and it is **very** strange if you want to understand the code, to see constructs like this :-)

**Comment by kris-nova** [comment]
Hi, so this is a reflection of our migration strategy and not our inability to understand Go.

We know it's weird, and we are working on refactoring it. #572 was the first step in this effort.
