### ISSUE TITLE
Using DO Provider does not yeild a Kubectl config

### ISSUE THREAD

**Issue by bscott** [kubicorn/kubicorn#595]
When building a cluster with provider of DO, a config is not generated and `getconfig` does not work. 

```
2018-03-18T14:30:11-07:00 [✔]  Created Firewall [REDACTED]
2018-03-18T14:30:13-07:00 [✔]  Created Firewall [REDACTED3]
2018-03-18T14:30:13-07:00 [ℹ]  Updating state store for cluster [REDACTED-do]
~ $
```

```
~ $ kubicorn getconfig test-do
2018-03-18T14:39:23-07:00 [ℹ]  Selected [fs] state store
2018-03-18T14:39:23-07:00 [ℹ]  Loaded cluster: REDACTED-do
2018-03-18T14:39:23-07:00 [ℹ]  Init Cluster
2018-03-18T14:39:24-07:00 [✖]  file does not exist
~ $
```

**Comment by xmudrii** [comment]
Hello @bscott!

What Kubicorn version are you running (you should be able to check this by running `kubicorn version`)?
We had some API changes in #572, and currently DO is not working with the latest version.

I've submitted #592 to fix those problems, and once it's merged, DigitalOcean should start working as expected.

If you want to test this right now, you can use the `digitalocean-hotfix` branch which contains the needed fixes.

**Comment by bscott** [comment]
Hi @xmudrii 

```
Kubicorn version:  {"Version":"0.0.003","GitCommit":"","BuildDate":"2018-03-18 22:33:09.729822867 +0000 UTC","GOVersion":"go1.10","GOARCH":"amd64","GOOS":"darwin"}
```

**Comment by xmudrii** [comment]
This doesn't contains the `GitCommit`, so I can't really tell on what revision are you.

Can you use `git log` or something to check what's the latest commit?

If you're before #572, you can set the `KUBICORN_ENVIRONMENT` environment variable to `LOCAL` and then to give it a try.

**Comment by kris-nova** [comment]
This brings up a good point - right now our version is respecting the `VERSION` file (good) but we aren't updating the file - maybe we should add something to `make` to write this in?

**Comment by xmudrii** [comment]
‎I've created an issue for tracing the `VERSION` problem -- #593
