### ISSUE TITLE
Use kubicorn to deploy a cluster to existing hosts

### ISSUE THREAD

**Issue by apobbati** [kubicorn/kubicorn#629]
Is kubicorn able to provision a cluster if I have existing machines? How would I go about implementing a provider to be able to accomplish this?

**Comment by xmudrii** [comment]
Currently not. We have plans for the `adopt` command for existing clusters, but it's on hold. We'll have more information about the command as we get kubicorn/controller more stable and fully-switch to the new cluster API.

**Comment by apobbati** [comment]
Thanks for the update! I'd like to contribute. Please point me in the right direction.

**Comment by xmudrii** [comment]
Hi @apobbati! I'm happy to hear you'd like to contribute to the project! Sorry for my late response, it has been a very busy week.

This is a large issue, so we want to make sure we plan it right. Before I give you some directions on how to do it and where to look into, I would love @kris-nova to let us know what does she thinks about the problem and is it good time to solve it now, or after we fully-implement cluster API.

If you have any idea how to solve the problem, let us know. You can also join our open developer calls to discuss it with us (calls are held biweekly, 1pm PST. For calendar invite, join our [mailing list](https://groups.google.com/forum/#!forum/kubicorn-users-and-developers)).

**Comment by apobbati** [comment]
@xmudrii @kris-nova Sounds like a plan! I'm a little new to Golang but I've provisioned Kubernetes clusters with other installers, so at this point i'm wondering what is the Kubicorn way to solve this problem.

**Comment by adrianog** [comment]
Has there been any progress on this?

**Comment by xmudrii** [comment]
@adrianog As far as I know there's still no progress on this issue.
