### ISSUE TITLE
using ovh profile and "invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by tk999** [kubicorn/kubicorn#657]
TKs-MacBook-Pro:~ tk$ kubicorn apply myfirstk8s
2018-07-27T09:55:17-07:00 [ℹ]  Selected [fs] state store
2018-07-27T09:55:17-07:00 [ℹ]  Loaded cluster: myfirstk8s
2018-07-27T09:55:17-07:00 [ℹ]  Init Cluster
2018-07-27T09:55:18-07:00 [ℹ]  Query existing resources
2018-07-27T09:55:20-07:00 [ℹ]  Resolving expected resources
2018-07-27T09:55:20-07:00 [ℹ]  Reconciling
2018-07-27T09:55:21-07:00 [ℹ]  Using existing KeyPair [myfirstk8s]
2018-07-27T09:55:22-07:00 [✔]  Created Network [9b9e393b-a7dc-4a4f-8f8a-b48ed7f93cb1]
2018-07-27T09:55:23-07:00 [✔]  Created Subnet [6bd6b876-0fcd-4057-ac60-2ba1b52fadf3]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x120 pc=0x1f0f477]

goroutine 1 [running]:
github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources.(*Subnet).Apply(0xc4207d4000, 0x2836c00, 0xc42039bc20, 0x2836c00, 0xc42039bc70, 0xc4201f2160, 0x0, 0x2836b40, 0xc42068dec0, 0x0, ...)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/cloud/openstack/operator/generic/resources/subnet.go:117 +0x357
github.com/kubicorn/kubicorn/cloud.(*AtomicReconciler).Reconcile(0xc4207a15a0, 0xc4201f2160, 0xc4201f2160, 0xc4201f2160, 0x0, 0x0)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/cloud/atomic_reconciler.go:119 +0x1e0
github.com/kubicorn/kubicorn/cmd.runApply(0xc420322180, 0x1184d00, 0xc420597cb0)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:145 +0x7d1
github.com/kubicorn/kubicorn/cmd.ApplyCmd.func1(0xc4203b3680, 0xc42020c3b0, 0x1, 0x1)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/cmd/apply.go:60 +0x6d
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).execute(0xc4203b3680, 0xc42020c360, 0x1, 0x1, 0xc4203b3680, 0xc42020c360)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:750 +0x2c1
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x34e0e40, 0xc420597f68, 0x214badc, 0x26a32c9)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:831 +0x2e4
github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra.(*Command).Execute(0x34e0e40, 0xc4200c2058, 0x0)
	/Users/tk/go/src/github.com/kubicorn/kubicorn/vendor/github.com/spf13/cobra/command.go:784 +0x2b
github.com/kubicorn/kubicorn/cmd.Execute()
	/Users/tk/go/src/github.com/kubicorn/kubicorn/cmd/root.go:76 +0x2d
main.main()
	/Users/tk/go/src/github.com/kubicorn/kubicorn/main.go:22 +0x20

**Comment by xmudrii** [comment]
Hi @tk999, thank you so much for reporting the issue!

The stack trace is very useful here, but I'm having hard time debugging it as I don't have access to OVH. Anyways, I will try my best to it and will let you know once it is ready for test.

To make the issue tracker and the progress of fixing the issue easier to track, I'm going to close this issue in favor of #655, as it describes the same problem.

Thank you so much!

**Comment by xmudrii** [comment]
@tk999 I've deployed a fix in #659 that could fix the problem. I don't have access to OVH, so I can't test it.

You need to update to the latest version of `kubicorn` using `git` or `go`, such as:
```
go get -u github.com/kubicorn/kubicorn/...
```

Before applying the cluster, you have to remove the cluster state and create a new one (`kubicorn create`), as there are some changes in the file structure.

If you still have problems, please post the error or stack trace if there is any.

Thank you so much!
